## Arrays & Lists

In [8]:
import numpy as np

x = [1, 2, 3]
y = [4, 5, 6]
xvec = np.array([7, 8, 9])
yvec = np.array([10, 11, 12])

print(x, x[0], x[2])
print(xvec, xvec[0], xvec[2])

[1, 2, 3] 1 3
[7 8 9] 7 9


### Adição
É possível fazer concatenação de listas ou adicionar itens em listas

In [11]:
x, y = [1, 2], [3, 4]
xvec, yvec = np.array([5, 6]), np.array([7, 8])

print(x + y, x + [10])
print(xvec + yvec, xvec + 10)

[1, 2, 3, 4] [1, 2, 10]
[12 14] [15 16]


### Multiplicação

In [12]:
print(xvec * yvec)
print(2 * x, 2 * xvec)

[35 48]
[1, 2, 1, 2] [10 12]


### Exponenciação

In [13]:
print(xvec ** 2)

[25 36]


### Conversão
É possível realizar a conversão de array para lista e de lista para array.

In [15]:
x = [1, 2, 3]
newArray = np.array(x)
print(newArray)

[1 2 3]


In [20]:
v = np.array([1, 2, 3])
newList = v.tolist()
print(newList)

[1, 2, 3]


### Fibonacci

In [24]:
N = int(input('Number os terms (Fibonacci sequence):'))
f = [0 for i in range(N)]
f[0], f[1] = 1, 1
for i in range(2, N):
    f[i] = f[i - 1] + f[i - 2]
print(f)

Number os terms (Fibonacci sequence):10
[1, 1, 2, 3, 5, 8, 13, 21, 34, 55]


## Matrices

In [27]:
L = [[1, 2], [3, 4]]
A = np.array(L)
M = np.matrix(L)

print(A)
print(A * A) #product between corresponding components
print(M * M) #matrix product

[[1 2]
 [3 4]]
[[ 1  4]
 [ 9 16]]
[[ 7 10]
 [15 22]]


In [29]:
rows, columns = 2,2
L = [[(i * j) for j in range(columns)] for i in range(rows)]

A, M = np.array(A), np.array(A)
print(A)
print(L[1][1])
print(A[1][1])
print(M.item(1, 1))

[[1 2]
 [3 4]]
1
4
4
